data_config:
  batch_size: 128

model_config:
  atom_encoder: true
  use_edge_attr: false
  model_name: PNA
  hidden_size: 80
  n_layers: 4
  dropout_p: 0.3
  aggregators:
    - mean
    - min
    - max
    - std
  scalers: false
  pretrain_lr: 0.01
  pretrain_epochs: 200
  pretrain_wd: 3.0e-6
  pretrain_scheduler:
    patience: 20
    factor: 0.5
    threshold: 0.0001

shared_config:
  learn_edge_att: false
  precision_k: 5
  num_viz_samples: 0
  viz_interval: 10
  viz_norm_att: true
  extractor_dropout_p: 0.5

GSAT_config:
  method_name: 'GSAT'
  pred_loss_coef: 1
  info_loss_coef: 1
  epochs: 100
  lr: 1.0e-3
  weight_decay: 3.0e-6

  from_scratch: true
  fix_r: false
  decay_interval: 10
  decay_r: 0.1
  final_r: 0.7
